data:
  data_dir: 'data/lyricskor'
model:
  batch_size: 32
  grad_clip: 5.0
  input_keep_prob: 0.8
  log_dir: 'logs'
  num_layers: 3
  output_keep_prob: 0.8
  rnn_size: 512
  seq_length: 100
train:
  train_steps: 200000
  model_dir: 'ballad_checkpoints'
  save_every: 1000
  learning_rate: 0.001
  loss_hook_n_iter: 1000
  check_hook_n_iter: 2000
  min_eval_frequency: 1000
